version: 2

project_name: tdl-archive

builds:
  - binary: tdl-archive
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
    mod_timestamp: '{{ .CommitTimestamp }}'
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - formats:
      - binary
    name_template: '{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}'

checksum:
  name_template: checksums.txt

release:
  github:
    owner: yshalsager
    name: tdl-archive

changelog:
  sort: asc
