version: 2

project_name: tdl-archive

builds:
  - binary: tdl-archive
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
    mod_timestamp: '{{ .CommitTimestamp }}'
    goos:
      - darwin
      - freebsd
      - linux
      - windows
    goarch:
      - '386'
      - amd64
      - arm
      - arm64
    goarm:
      - '5'
      - '6'
      - '7'

archives:
  - formats:
      - binary
    name_template: '{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}'

checksum:
  name_template: checksums.txt

release:
  github:
    owner: yshalsager
    name: tdl-archive

changelog:
  sort: asc
