name: CI

on:
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: read
  pull-requests: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: jdx/mise-action@v5.1.1
      - run: golangci-lint run
        env:
          GOMAXPROCS: ''
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: jdx/mise-action@v5.1.1
      - run: go test ./...
        env:
          GOMAXPROCS: ''
      - run: go vet ./...
        env:
          GOMAXPROCS: ''
      - run: go build -trimpath -o dist/tdl-archive .
        env:
          GOMAXPROCS: ''
