name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: Tag to release
        required: true
        type: string

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.tag || github.ref }}
      - uses: jdx/mise-action@v5.0.1
      - run: goreleaser release --clean
        env:
          GOMAXPROCS: ''
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
